# Generated by Django 6.0.6 on 2026-06-05 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='market',
            field=models.CharField(max_length=100),
        ),
    ]
